repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.3.4'
    hooks:
      - id: ruff-format
        files: "^src/"
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        files: "^src/"
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-vcs-permalinks
      - id: debug-statements
        exclude: ^projects/fal/src/fal/cli/debug.py
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.3.0"
    hooks:
      - id: mypy
        args:
          [
            "--ignore-missing-imports",
            "--no-warn-no-return",
            "--check-untyped-defs",
          ]
        additional_dependencies:
          - types-protobuf
          - types-requests
          - types-redis
          - types-pyyaml
        files: "^src/"
